In [2]:
import pandas as pd

events = pd.read_csv(
    "../data/Astram event data_anonymized - Astram event data_anonymizedb40ac87.csv"
)

events.head()

,id,event_type,latitude,longitude,endlatitude,endlongitude,address,end_address,event_cause,requires_road_closure,...,resolved_at_address,resolved_at_latitude,resolved_at_longitude,closed_by_id,closed_datetime,resolved_by_id,resolved_datetime,gba_identifier,zone,junction
0,FKID000000,unplanned,13.040004,77.518099,0.000000,0.000000,"Mumbai Bengaluru Highway, Jalahalli Cross Junc...",NaN,vehicle_breakdown,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FKID000001,unplanned,12.921876,77.645158,0.000000,0.000000,"19th Main Road, Heavie Halcyon, Agara, HSR Lay...",NaN,vehicle_breakdown,False,...,"19th Main Road, Heavie Halcyon, Agara, HSR Lay...",12.921876,77.645158,NaN,NaN,FKUSR00002,2024-01-30 04:17:46.828355+00,NaN,NaN,NaN
2,FKID000002,unplanned,12.955622,77.585708,0.000000,0.000000,"Lalbagh Main Road, Dr Sri Shantaveera Swami Ci...",NaN,others,False,...,NaN,NaN,NaN,FKUSR00003,2024-01-30 04:56:03.281509+00,NaN,NaN,Bengaluru Central Corporation,Central Zone 2,UrvashiJunction
3,FKID000003,unplanned,13.006147,77.579435,13.006239,77.579516,"Sankey Road, Bashyam Circle, Sadashiva Nagar, ...","Sankey Road, Palace Orchard Upper, Sadashiva N...",tree_fall,True,...,NaN,NaN,NaN,FKUSR00004,2024-03-14 07:42:05.54944+00,NaN,NaN,NaN,NaN,NaN
4,FKID000004,unplanned,12.953980,77.585233,0.000000,0.000000,"Lalbagh Fort Road, Lalbagh Main Gate Junction,...",NaN,vehicle_breakdown,False,...,NaN,NaN,NaN,FKUSR00003,2024-01-30 05:35:17.338283+00,NaN,NaN,NaN,NaN,LalbaghMainGateJunc

In [3]:
events.shape

(8173, 46)

In [4]:
events.columns.tolist()

['id',
 'event_type',
 'latitude',
 'longitude',
 'endlatitude',
 'endlongitude',
 'address',
 'end_address',
 'event_cause',
 'requires_road_closure',
 'start_datetime',
 'end_datetime',
 'status',
 'authenticated',
 'modified_datetime',
 'map_file',
 'direction',
 'description',
 'veh_type',
 'veh_no',
 'corridor',
 'priority',
 'cargo_material',
 'reason_breakdown',
 'age_of_truck',
 'created_date',
 'route_path',
 'client_id',
 'created_by_id',
 'last_modified_by_id',
 'assigned_to_police_id',
 'citizen_accident_id',
 'comment',
 'police_station',
 'meta_data',
 'kgid',
 'resolved_at_address',
 'resolved_at_latitude',
 'resolved_at_longitude',
 'closed_by_id',
 'closed_datetime',
 'resolved_by_id',
 'resolved_datetime',
 'gba_identifier',
 'zone',
 'junction']

In [5]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8173 entries, 0 to 8172
Data columns (total 46 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     8173 non-null   object
 1   event_type             8173 non-null   object
 2   latitude               8173 non-null   float64
 3   longitude              8173 non-null   float64
 4   endlatitude            8004 non-null   float64
 5   endlongitude           8004 non-null   float64
 6   address                8170 non-null   object
 7   end_address            687 non-null    object
 8   event_cause            8173 non-null   object
 9   requires_road_closure  8173 non-null   bool
 10  start_datetime         8173 non-null   object
 11  end_datetime           490 non-null    object
 12  status                 8173 non-null   object
 13  authenticated          8173 non-null   object
 14  modified_datetime      8173 non-null   object
 15  map_file               0 non-null      float64
 16  direction              43 non-null     object
 17  description            6813 non-null   object
 18  veh_type               4887 non-null   object
 19  veh_no                 4886 non-null   object
 20  corridor               8153 non-null   object
 21  priority               8171 non-null   object
 22  cargo_material         276 non-null    object
 23  reason_breakdown       276 non-null    object
 24  age_of_truck           276 non-null    float64
 25  created_date           8173 non-null   object
 26  route_path             137 non-null    object
 27  client_id              8173 non-null   int64
 28  created_by_id          8171 non-null   object
 29  last_modified_by_id    8170 non-null   object
 30  assigned_to_police_id  128 non-null    object
 31  citizen_accident_id    128 non-null    object
 32  comment                0 non-null      float64
 33  police_station         8173 non-null   object
 34  meta_data              0 non-null      float64
 35  kgid                   7914 non-null   object
 36  resolved_at_address    74 non-null     object
 37  resolved_at_latitude   74 non-null     float64
 38  resolved_at_longitude  74 non-null     float64
 39  closed_by_id           3141 non-null   object
 40  closed_datetime        3141 non-null   object
 41  resolved_by_id         74 non-null     object
 42  resolved_datetime      74 non-null     object
 43  gba_identifier         3444 non-null   object
 44  zone                   3444 non-null   object
 45  junction               2510 non-null   object
dtypes: bool(1), float64(10), int64(1), object(34)
memory usage: 2.8+ MB

In [6]:
events.isnull().sum().sort_values(
    ascending=False
)

comment                  8173
map_file                 8173
meta_data                8173
direction                8130
resolved_at_address      8099
resolved_at_latitude     8099
resolved_by_id           8099
resolved_datetime        8099
resolved_at_longitude    8099
assigned_to_police_id    8045
citizen_accident_id      8045
route_path               8036
age_of_truck             7897
reason_breakdown         7897
cargo_material           7897
end_datetime             7683
end_address              7486
junction                 5663
closed_datetime          5032
closed_by_id             5032
gba_identifier           4729
zone                     4729
veh_no                   3287
veh_type                 3286
description              1360
kgid                      259
endlongitude              169
endlatitude               169
corridor                   20
address                     3
last_modified_by_id         3
priority                    2
created_by_id               2
authenticated               0
event_cause                 0
id                          0
longitude                   0
latitude                    0
event_type                  0
status                      0
start_datetime              0
requires_road_closure       0
client_id                   0
created_date                0
modified_datetime           0
police_station              0
dtype: int64

In [7]:
events.describe(include="all")

,id,event_type,latitude,longitude,endlatitude,endlongitude,address,end_address,event_cause,requires_road_closure,...,resolved_at_address,resolved_at_latitude,resolved_at_longitude,closed_by_id,closed_datetime,resolved_by_id,resolved_datetime,gba_identifier,zone,junction
count,8173,8173,8173.000000,8173.000000,8004.000000,8004.000000,8170,687,8173,8173,...,74,74.000000,74.000000,3141,3141,74,74,3444,3444,2510
unique,8173,2,NaN,NaN,NaN,NaN,3089,561,17,2,...,58,NaN,NaN,1225,3141,42,74,5,10,294
top,FKID008172,unplanned,NaN,NaN,NaN,NaN,"Outer Ring Road, Karthik Nagar, Marathahalli, ...","Outer Ring Road, CQAE Staff Quarters, Yeshwant...",vehicle_breakdown,False,...,"Yeshwanthpura TTMC Bus Stand Road, Salarpuria ...",NaN,NaN,FKUSR00105,2024-01-30 02:07:14.594818+00,FKUSR01665,2024-01-30 04:17:46.828355+00,Bengaluru Central Corporation,Central Zone 2,MekhriCircle
freq,1,7706,NaN,NaN,NaN,NaN,88,6,4896,7497,...,8,NaN,NaN,54,1,8,1,892,623,64
mean,NaN,NaN,12.987076,77.596034,1.128050,6.678011,NaN,NaN,NaN,NaN,...,NaN,13.002599,77.569049,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,0.060109,0.061193,3.736845,21.761316,NaN,NaN,NaN,NaN,...,NaN,0.091377,0.057246,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,12.801041,77.308731,0.000000,0.000000,NaN,NaN,NaN,NaN,...,NaN,12.841568,77.390820,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,12.951635,77.556747,0.000000,0.000000,NaN,NaN,NaN,NaN,...,NaN,12.947656,77.543782,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,12.982847,77.589460,0.000000,0.000000,NaN,NaN,NaN,NaN,...,NaN,12.983715,77.556135,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,13.026867,77.625853,0.000000,0.000000,NaN,NaN,NaN,NaN,...,NaN,13.019590,77.589899,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,13.267510,77.769403,59.860133,80.720691,NaN,NaN,NaN,NaN,...,NaN,13.257297,77.712662,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
events["priority"].value_counts(dropna=False)